config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/movies')
  get 'movies_add_to_favorites/:id', to: 'movies#addToFavorites', as: 'add_to_favorites'
  get 'movies_remove_from_favorites/:id', to: 'movies#removeFromFavorites', as: 'remove_from_favorites'
  get 'recomendations', to: 'movies#recomendations', as: 'recomendations'
  resources :movies
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
	def self.already_liked_by(user_id, movie_id)
		movie = Movie.where("user_id = ? and movie_id = ?", user_id, movie_id)
		if movie == nil
			return false
		else
			return true
		end
	end

	def self.all_liked_by(user_id)
		movies = Movie.all
		users_movies = UserMovie.where("user_id =  ?", user_id)
		movies.each do |movie|
			users_movies.each do |like|
				if movie.id == like.movie_id.to_i
					movie.liked_by_user = true
				end
			end
		end
		return movies
	end

	def self.was_liked_by_user
		@liked_by_user
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all_liked_by(current_user.id)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /movies_add_to_favorites/1
  def addToFavorites
	# a user likes a movie if is stored in UserMovie associated table
		user_movie = UserMovie.create(movie_id: params[:id], user_id: current_user.id) # at this point is always guarranteed a login
		respond_to do |format|
			format.html { redirect_to movies_url, notice: 'you like this movie!' }
        	format.json { head :no_content }
		end
  end

  # GET /romove_from_favorites/1
  def removeFromFavorites
	user_movie = UserMovie.where("user_id = ? and movie_id = ?", current_user.id, params[:id])
	user_movie.each do |um|
		um.destroy
	end
	respond_to do |format|
		format.html { redirect_to movies_url, notice: 'you dislike this movie!' }
        format.json { head :no_content }
	end
  end

  def recomendations
	fav_movies_ids = UserMovie.where("user_id = ?", current_user.id) # retrieve all liked movies from current user
	favorite_movies = []
	Movie.all_liked_by(current_user.id).each do |movie| # Here we prefer fetch all movies vs retrieve each favorite movie for performance purposes
		fav_movies_ids.each do |fav_movie|
			if movie.id == fav_movie.movie_id.to_i
				favorite_movies.push(movie)
			end
		end
	end
	@recommended_movies = favorite_movies
	# After add recommendations model then add the genre field in the movie form.
	# Then compute in this action the most genre viewed of your favorite movies
	# Then display the first ten movies of that genre
	# That's the recomendation
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OmniBNKChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">The OmniBNK App</a>
        </div>
        <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
				<li><a href="/movies">Movies</a></li>
				<li><a href="/recomendations">Recomendations</a></li>
        </ul>
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
        </p>
        </div>
    </div>
	</nav>

	<div class="container">
		<div class="row">
		<% if notice %>
				<p class="alert alert-success">
					<%= notice %>
				</p>
		<% end %>
		<% if alert %>
				<p class="alert alert-danger">
					<%= alert %>
				</p>
		<% end %>
		</div>
		<div class="row">
				<%= yield %>
		</div>
	</div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.description %></td>
        <td><%= link_to 'Show', movie %></td>
		<td><%= link_to 'Edit', edit_movie_path(movie) %></td>
		<% if movie.liked_by_user %>
			<td><%= link_to 'RemoveFromFavorites', remove_from_favorites_path(movie) %></td>
		<% else %> 
			<td><%= link_to 'AddToFavorites', add_to_favorites_path(movie) %></td>
		<% end %>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/recomendations.html.erb
<h1>Recommendations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommended_movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.description %></td>
        <td><%= link_to 'Show', movie %></td>
		<td><%= link_to 'Edit', edit_movie_path(movie) %></td>
		<% if movie.liked_by_user %>
			<td><%= link_to 'RemoveFromFavorites', remove_from_favorites_path(movie) %></td>
		<% else %> 
			<td><%= link_to 'AddToFavorites', add_to_favorites_path(movie) %></td>
		<% end %>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>